### ISSUE TITLE
[question] - init slider from outside the script file?

### ISSUE THREAD

**Issue by thednp** [cferdinandi/slider#20]
Hi. I'm developing an all in slider based on your code, I'm a novice Vanilla JS coder and keep getting errors when initiating the slider function outside the script file. I moved your sexy scrip into it's file. I noticed that removing the code wrappers help, but I'm not sure of anything and I haven't found any documentation on this yet.

Thanks for your time :)

**Comment by cferdinandi** [comment]
@thednp This is largely not my code. It was forked from the (now defunct) [SwipeJS](https://github.com/thebird/Swipe).

You should be able to initialize the script from an external file **or** inline, but the `slider.js` file must be loaded first, *and* the slider elements you'd like to initialize should be loaded, too. The script doesn't wait for the document to be ready before trying to run, so if you attempt to run in it before the DOM elements are their, it will fail.

As such, you should almost always put it in the footer.
