### ISSUE TITLE
Put on NPM?

### ISSUE THREAD

**Issue by dgsunesen** [cferdinandi/slider#21]
Hi there,

Any chance you could add this to npm? :)

Thanks.

**Comment by cferdinandi** [comment]
No, sorry. Slider has been deprecated:

> Slider has been deprecated and is no longer maintained. Neither currently open nor new issues will be addressed.

> Increasing amounts of data indicate how ineffective sliders are are driving business goals in web design. They often represent an inability of key stakeholders to reach consensus.

> When they do serve a focused purpose (for example, image carousels), an alternate design pattern would often better serve the user's goals (for example, just displaying all of the images full-width in a stack).

> Beyond pure UX-driven reasons, there are numerous bugs that keep popping up, the original script this was forked from (SwipeJS) is no longer being maintained. I won't be closing the repository, so you'll still be able to access the script and documentation, but I won't be supporting or maintaining it any longer.
