### ISSUE TITLE
Can't swipe on touch decive when the slide is a iframe

### ISSUE THREAD

**Issue by qinyuanbin** [cferdinandi/slider#23]
I just try the demo you have given in touch model of chrome, fourth page can't not swipe :smile:

**Comment by cferdinandi** [comment]
Per the docs, deprecated and unsupported

**Comment by qinyuanbin** [comment]
Sorry. But I am having a problem on this situation and can't figure out a good way to solve it

**Comment by cferdinandi** [comment]
This script is deprecated and not maintained. Check out the README for additional information and some active we developed alternatives.
